version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc:
      "Generate code from protofiles"
    cmds:
      - protoc -I api/grpc/proto api/grpc/proto/*.proto --go_out=api/grpc/gen --go_opt=paths=source_relative --go-grpc_out=api/grpc/gen --go-grpc_opt=paths=source_relative
